---
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-faker
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - ".bundle/**/*"
    - "bin/bundle"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/bundle/**/*"
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.0.1

Bundler:
  Enabled: true
Faker:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/devise.rb"
Lint:
  Enabled: true
Metrics:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - "db/**/*"
  Max: 24
Metrics/BlockLength:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
  Max: 40
Metrics/MethodLength:
  Exclude:
    - "db/**/*"
Migration:
  Enabled: true
Naming:
  Enabled: true
Naming/InclusiveLanguage:
  Exclude:
    - "Gemfile"
    - "config/environments/production.rb"
Packaging:
  Enabled: true
Performance:
  Enabled: true
RSpec:
  Enabled: true
RSpec/ImplicitSubject:
  Enabled: false
RSpec/Capybara:
  Enabled: true
RSpec/FactoryBot:
  Enabled: true
RSpec/FilePath:
  Enabled: false
RSpec/Rails:
  Enabled: true
Rails:
  Enabled: true
Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/**/*active_storage*"
Rails/FilePath:
  Enabled: false
Security:
  Enabled: true
Style:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - "db/**/*"
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/GlobalVars:
  AllowedVariables:
    - $redis